### ISSUE TITLE
Adapting to vega leaflet-style lib?

### ISSUE THREAD

**Issue by nyurik** [omnisci/omnisci-vega-mapboxgl-demo-philly-parking#3]
Hi, a long time ago I wrote https://github.com/nyurik/leaflet-vega - a plugin for Vega, where user can specify a vega graph to be drawn on top of a life map (leaflet based).  Do you think your code could be integrated with that lib, or maybe a new mapbox-based lib should be made with a similar approach?  Ideally something that will be easily swappable depending on which tiling library user needs in their app?

Thanks!

**Comment by randyzwitch** [comment]
Thanks for stopping by @nyurik! Unfortunately, this isn't as straightforward as swapping one vega for another. The "vega" that OmniSci uses is heavily customized for functionality that OmniSci feels is important to render graphics on GPU, but not necessarily relates to v1/v2/v3/v4 of vega. So our backend wouldn't understand an arbitrary vega spec passed to it.

We have identified making "our" version of vega closer to the v4 version of vega, but I don't have any insight into the timing when we might do that.

**Comment by nyurik** [comment]
Oh, I was wondering why there was no vega lib dependency in `package.json`.  Do you know if it would be possible to join the efforts, so that Vega could be improved, and we can all work on the same codebase?  I think Vega code might need some cleaning up (styling and performance), but having forked versions probably won't help the whole Vega-loving community to make it better :)

Regardless, I'm very impressed by your efforts!  Thanks for working on it!  Sorry I used issues for messaging (github doesn't have any other reasonable messaging mechanism  :)).  Plus maybe others might participate.

**Comment by randyzwitch** [comment]
In this case, probably not. The exposed vega functionality is a smaller piece of our larger enterprise product [Immerse](https://www.omnisci.com/platform/immerse) for in-GPU rendering of very large datasets, where it would be infeasible to stream the data to the client (think millions or billions of geospatial objects). vega is more of an implementation detail in this case for its declarative visualization grammar, we just also happen to expose this functionality to users to build custom apps if they'd like (which this repo is an example of). I agree that it's not ideal that we're not following the exact spec...whether that's considered technical debt or not, our rendering engineers will have to figure that out as time goes on.

We are working with the vega folks in many cases, [Falcon](https://idl.cs.washington.edu/papers/falcon/) is one such example. Jeff Heer is also one of our company advisers. So we are trying to figure out how we can use vega proper in combination with our GPU-based data platform.
